version: "3.8"
services:
  kudo-arxiv2018:
    build:
      context: ./docker
    volumes: 
      - .:/work
    runtime: nvidia
    environment:
        - NVIDIA_VISIBLE_DEVICES=all
        - NVIDIA_DRIVER_CAPABILITIES=all
    deploy:
        resources:
            reservations:
                devices:
                    - driver: nvidia
                      capabilities: [gpu, utility]
